### ISSUE TITLE
Test Run 

### ISSUE THREAD

**Issue by archiash** [Harukaah/Scratch-Project#13]

**Comment by fusenattawat** [comment]
https://github.com/Harukaah/Scratch-Project/assets/141806694/3a7d3179-ed33-4e31-966a-ea04712f3c13
Test รอบแรกเกิดการ Bug
เวลากดเดิน มันทะลุกำแพง ไปโผล่อีกฝั่ง

**Comment by fusenattawat** [comment]
![bug](https://github.com/Harukaah/Scratch-Project/assets/141806694/b21c6376-3cc4-49a4-9bb4-421c64e920d4)
เกิด การ bug เวลาการเกิดของ crystal ที่ทำ hit boss มันเกิดซ้อนกัน ถึง 2 crystal

**Comment by fusenattawat** [comment]
https://github.com/Harukaah/Scratch-Project/assets/141806694/d5666bf6-4821-4beb-b9a8-786c5bfb4819

เกิดการ bug ตำแหน่งสกิลของ Reaper ไม่ถูกต้องเวลาเล่นอีกรอบ
