### ISSUE TITLE
Test Full Run

### ISSUE THREAD

**Issue by archiash** [Harukaah/Scratch-Project#14]

**Comment by fusenattawat** [comment]
https://github.com/Harukaah/Scratch-Project/assets/141806694/1b863e27-ee0d-45d2-889b-09935ffe842d

ตัว เกมส์ มีความสมบูรณ์ ไม่ พบ bug อะไรเพิ่มเติม bug ที่พบก่อนหน้านี้ได้รับการแก้ไขปัญหา ไปเรียบร้อยแล้ว พร้อมนำเกมส์ไป สู่สายตาชาวโลกในวันพรุ่งนี้แล้ว
