### ISSUE TITLE
Presentation slide

### ISSUE THREAD

**Issue by archiash** [Harukaah/Scratch-Project#2]

**Comment by NNNewwear** [comment]
Present-01 (เผื่อมี 02 ตามมา)
อยากแก้ไรบอกได้
[Present.pdf](https://github.com/Harukaah/Scratch-Project/files/12455711/Present.pdf)

**Comment by archiash** [comment]
https://www.canva.com/design/DAFszymmXA0/0Tdw4dAJxwFZ18ET5t8sKQ/edit?utm_content=DAFszymmXA0&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton
Presentation Slide
