### ISSUE TITLE
VFX n More Graphic

### ISSUE THREAD

**Issue by Harukaah** [Harukaah/Scratch-Project#20]
includes animation, vfx of attacks, death vfx

**Comment by Harukaah** [comment]
To do:
 - Slash effect when player picked the crystal

**Comment by archiash** [comment]
![1694305250250.jpg](https://github.com/Harukaah/Scratch-Project/assets/46347714/803c8fe3-ebeb-4782-acde-9c3bd22e3155)

![1694305249564.jpg](https://github.com/Harukaah/Scratch-Project/assets/46347714/70e3d42c-fe1d-4ba1-b3b3-520616a67dc8)

**Comment by archiash** [comment]
![bg2re](https://github.com/Harukaah/Scratch-Project/assets/46347714/3c0642a0-9995-4cf5-b93d-7b9d031ff324)
![lightningFX](https://github.com/Harukaah/Scratch-Project/assets/46347714/8812eb17-dd24-415c-af4c-97bd26c0e639)
![reaperProj](https://github.com/Harukaah/Scratch-Project/assets/46347714/09ec7641-31af-4a5a-af59-ee1552e81c65)
![reaperProjFX](https://github.com/Harukaah/Scratch-Project/assets/46347714/64b963fe-e7e6-4f6c-a950-619b63cf0535)
![bg1](https://github.com/Harukaah/Scratch-Project/assets/46347714/b3b9059f-4d83-42fb-ba11-5b219d35bb98)

**Comment by archiash** [comment]
![Artboard 1](https://github.com/Harukaah/Scratch-Project/assets/46347714/79d4ed96-b362-4d4c-bf52-60a5844f9875)
