### ISSUE TITLE
Meeting #2

### ISSUE THREAD

**Issue by fusenattawat** [Harukaah/Scratch-Project#21]
![IMG_0958](https://github.com/Harukaah/Scratch-Project/assets/141806694/854f5308-8b85-41fd-b0c4-f9ac2de51bb1)

**Comment by NNNewwear** [comment]
ประชุม week 2 (4/06/2023) นัดพูดคุยเกี่ยวกับเกม การเล่นเกม หาบัคในเกม ดีไซน์ภาพพื้นหลัง, ตัวละคร, เอฟเฟค
