### ISSUE TITLE
UX/UI

### ISSUE THREAD

**Issue by Harukaah** [Harukaah/Scratch-Project#22]
start screen and end screen

**Comment by archiash** [comment]
![1694305249868.jpg](https://github.com/Harukaah/Scratch-Project/assets/46347714/d8d44eea-1a15-4db4-8bac-bc4aebb9487e)

**Comment by archiash** [comment]
![1694305332963.jpg](https://github.com/Harukaah/Scratch-Project/assets/46347714/c2dd472d-03b6-4b03-b79a-2f319feaa17b)

![1694305333515.jpg](https://github.com/Harukaah/Scratch-Project/assets/46347714/e3a7277b-2aea-45d5-afcf-4c236675953c)

![1694305335178.jpg](https://github.![1694305334223.jpg](https://github.com/Harukaah/Scratch-Project/assets/46347714/6e53427e-af6d-48d4-8fdd-5691ae06ca36)

46347714/4ffbffc8-d1d7-4f34-a384-d81![1694305335503.jpg](https://github.com/Harukaah/Scratch-Project/assets/46347714/adffd5f4-c56a-402f-8a13-c86c139eb90c)

3.jpg …]()

![1694305334503.jpg](https://github.com/Harukaah/Scratch-Project/assets/46347714/fa8e3546-9f22-4b03-948b-25deabb8c27a)

![Uploading 1694305335503.jpg …]()

![1694305333220.jpg](https://github.com/Harukaah/Scratch-Project/assets/46347714/57821a7d-491f-4feb-b267-c5fbc48c51b6)

![1694305333791.jpg](https://github.com/Harukaah/Scratch-Project/assets/46347714/8708f08c-d4d2-485e-b2d3-2a85bd9d7e09)

![1694305332596.jpg](https://github.com/Harukaah/Scratch-Project/assets/46347714/a5deaed2-496a-44e8-8bce-e4a1bee4b276)

**Comment by archiash** [comment]
![1694305335178.jpg](https://github.com/Harukaah/Scratch-Project/assets/46347714/d162d69d-5a27-45c3-8ce3-0dc70139d512)

![1694305332963.jpg](https://github.com/Harukaah/Scratch-Project/assets/46347714/390dc338-ed0b-4d2a-9119-59e980e46da2)

![1694305334223.jpg](https://github.com/Harukaah/Scratch-Project/assets/46347714/b1fa83f3-84d7-4cf5-bad7-c80625685b39)

![1694305333220.jpg](https://github.com/Harukaah/Scratch-Project/assets/46347714/6c3f7a54-f9a9-4829-83c8-1a49cdc07ca7)

![1694305333515.jpg](https://github.com/Harukaah/Scratch-Project/assets/46347714/d0ea3dfc-d211-4e8c-8ae6-be9eb091d70f)

![1694305334873.jpg](https://github.com/Harukaah/Scratch-Project/assets/46347714/b65e164d-7f1f-4415-b246-e4e86ec81b77)

![1694305332596.jpg](https://github.com/Harukaah/Scratch-Project/assets/46347714/7529a4d3-8518-44e5-89ba-702e81fb2d86)

![1694305333791.jpg](https://github.com/Harukaah/Scratch-Project/assets/46347714/0c330dd4-c7cb-4d41-b5e3-61b60d59f097)

**Comment by archiash** [comment]
![theGirlName](https://github.com/Harukaah/Scratch-Project/assets/46347714/132ba933-ff27-44b6-ac45-79f986bb3c9c)

**Comment by archiash** [comment]
![MenuBG](https://github.com/Harukaah/Scratch-Project/assets/46347714/f9fc8be7-d075-4618-b5de-731d25c967a8)

**Comment by archiash** [comment]
![pxArt(1)](https://github.com/Harukaah/Scratch-Project/assets/46347714/afaf05bf-f902-41ce-9aaa-fd989c33bf73)
![pxArt](https://github.com/Harukaah/Scratch-Project/assets/46347714/bce0f4ed-8dcc-43e3-8ffc-5148f6d103ae)
![pxArt(2)](https://github.com/Harukaah/Scratch-Project/assets/46347714/23ca4185-de8f-4519-998c-bc276ce4900b)

**Comment by archiash** [comment]
![back@4x](https://github.com/Harukaah/Scratch-Project/assets/46347714/9f0a881c-dfc8-487e-a1f2-128166d3e57d)
![try@4x](https://github.com/Harukaah/Scratch-Project/assets/46347714/57e67bee-b739-4fe3-92b2-e774d32b25cd)
