### ISSUE TITLE
Meeting #3

### ISSUE THREAD

**Issue by NNNewwear** [Harukaah/Scratch-Project#24]

**Comment by fusenattawat** [comment]
![tempImageQidVyZ](https://github.com/Harukaah/Scratch-Project/assets/141806694/304686d4-a84e-47e6-be77-a55c6ba99f50)

**Comment by fusenattawat** [comment]
![tempImageBwJyL8](https://github.com/Harukaah/Scratch-Project/assets/141806694/56d32709-cd18-4aa3-851e-bb6386d59c60)

**Comment by NNNewwear** [comment]
ประชุม week 2 (5/06/2023) แก้บัคที่เจอในเกม ใส่รูปที่วาดลงในเกม คิดเรื่องที่จะทำใน ลองเล่นเกมที่แก้บัคแล้วและปรับสมดุลเกม คิดชื่อเกม( ยังไม่ลงตัว )
