### ISSUE TITLE
Meeting #1

### ISSUE THREAD

**Issue by NNNewwear** [Harukaah/Scratch-Project#25]

**Comment by fusenattawat** [comment]
![IMG_0957](https://github.com/Harukaah/Scratch-Project/assets/141806694/c93f84e1-51ee-4765-8767-e30d6fc05b01)

**Comment by fusenattawat** [comment]
![Uploading 7A669F64-7D99-4DC8-9BB6-CD1D8E8BC271.jpg…]()

**Comment by fusenattawat** [comment]
![7A669F64-7D99-4DC8-9BB6-CD1D8E8BC271](https://github.com/Harukaah/Scratch-Project/assets/141806694/a481b96d-7ad7-4c14-90b0-eade63e30152)

**Comment by NNNewwear** [comment]
ประชุม week 2 (3/06/2023) คุยกันเรื่องนัดประชุมในวันที่ 4 และ 5. ช่วยกันคิดรูปแบบตัวละคร, การโจมตีของบอส. แจกจ่ายงานให้แต่ละคนไปทำ เช่น ทำตัวเกม ทำกราฟิก
