### ISSUE TITLE
Game Graphic

### ISSUE THREAD

**Issue by archiash** [Harukaah/Scratch-Project#7]

**Comment by Harukaah** [comment]
Game Items:

- Crystals | Appear around the maze waiting to be picked up by the player to lower boss HP ✔
- Mana / Skill points | Shows the player how many times they can dash  ✔
- Boss and Player HP bar | Shows how much HP the sprite has left ✔
- Fireball | Mage attack skill ✔
- Sythe | Reaper attack skill
- Dark Void | ??? attack skill

**Comment by Harukaah** [comment]
Crystals | Completed 
![crystal ](https://github.com/Harukaah/Scratch-Project/assets/140624361/40fa86b0-09fd-4111-9e4c-560321a7be1a)

**Comment by Harukaah** [comment]
Mana Orb | Completed 
![mana orb](https://github.com/Harukaah/Scratch-Project/assets/140624361/335889ba-6797-4587-8c81-441616f31322)

**Comment by Harukaah** [comment]
Boss/Player HP | Completed
![Boss HP Player HP](https://github.com/Harukaah/Scratch-Project/assets/140624361/75429013-c92a-4759-8e4f-197bf8b5a974)

**Comment by Harukaah** [comment]
Fireball | Completed
![fireball1](https://github.com/Harukaah/Scratch-Project/assets/140624361/2d05e66f-4118-4de3-a607-a770c3a1b4ce)
![fireball2](https://github.com/Harukaah/Scratch-Project/assets/140624361/fe961823-913d-4c7b-ae98-dc6a99a71788)

**Comment by Harukaah** [comment]
the Mage | Final Design Completed
![IMG_9678](https://github.com/Harukaah/Scratch-Project/assets/140624361/451e5aa1-d79f-4225-8652-b490dd8d483f)
