### ISSUE TITLE
Sound Design

### ISSUE THREAD

**Issue by archiash** [Harukaah/Scratch-Project#8]

**Comment by fusenattawat** [comment]
<img width="1440" alt="ภาพถ่ายหน้าจอ 2566-09-12 เวลา 20 38 48" src="https://github.com/Harukaah/Scratch-Project/assets/141806694/2aba9dfa-1212-45e2-acfd-9d17db88dd73">

เสียงอินโทรเกมส์
https://drive.google.com/drive/folders/1ak8YeXcHbbgAeB6ZTxTu62-1Zcl0UIdz?usp=share_link

**Comment by fusenattawat** [comment]
https://github.com/Harukaah/Scratch-Project/assets/141806694/dc0e9c4e-3163-44f6-a2be-b3c6ffe00273

เสียง เลือก boss
https://drive.google.com/file/d/1sTpNbJEKSHCwfrO7DIaKmNrqIrjyj4ao/view?usp=share_link

**Comment by fusenattawat** [comment]
https://github.com/Harukaah/Scratch-Project/assets/141806694/492a2b1a-3ffd-461b-8de1-569ba316355d

เสียง ตอน fight กับ the reaper
[[]](https://drive.google.com/file/d/1ZUkCRsZV3yvLW4fJJN9rdCanW7-rzmi4/view?usp=share_link)(url)

**Comment by fusenattawat** [comment]
![IMG_877E19E344EB-1](https://github.com/Harukaah/Scratch-Project/assets/141806694/bdfc74af-9f4d-421a-83ff-918dd5f11ebd)
ท่า โจมตีพิเศษ ของ reaper
https://drive.google.com/file/d/13FERJopJxfWd4cGaW53qRZNOLHTpcod7/view?usp=share_link

**Comment by fusenattawat** [comment]
<img width="1440" alt="ภาพถ่ายหน้าจอ 2566-09-12 เวลา 21 15 40" src="https://github.com/Harukaah/Scratch-Project/assets/141806694/90dfdf69-00f9-4e89-940d-62a8161a6819">
เสียงตอน fight the girl




[](url[)](https://drive.google.com/file/d/1BN_o4mgilR0LtPE99TP4Y8Kw6VkGr85a/view?usp=share_link)

**Comment by fusenattawat** [comment]
<img width="1440" alt="ภาพถ่ายหน้าจอ 2566-09-12 เวลา 21 15 46" src="https://github.com/Harukaah/Scratch-Project/assets/141806694/aa661a79-1048-4d71-b90e-c61c69beb092">
[เสียงโจมตีธรรมดาของthegirl

[[]](https://drive.google.com/file/d/1LLbv1toNPDJRpPSGZgCTt9IBGx6DfwUu/view?usp=share_link)(url)

**Comment by fusenattawat** [comment]
![IMG_FC80BF5497C6-1](https://github.com/Harukaah/Scratch-Project/assets/141806694/e9494309-82e5-4f2c-ae53-922ad6686414)

ท่าโจมตีพิเศษ ของ​ the girl
[[]](https://drive.google.com/file/d/1PPAujuCleavHbk8F6y7jql60USFdGkBl/view?usp=share_link)(url)

**Comment by fusenattawat** [comment]
<img width="1440" alt="ภาพถ่ายหน้าจอ 2566-09-12 เวลา 21 42 13" src="https://github.com/Harukaah/Scratch-Project/assets/141806694/7901179d-0f19-46cc-9875-1016974305d7">
sound fight the mage 1

https://drive.google.com/file/d/1jXzqJHkgnCFWPpB7K2KIjvmjBNIxMSD2/view?usp=share_link

**Comment by fusenattawat** [comment]
<img width="1440" alt="ภาพถ่ายหน้าจอ 2566-09-12 เวลา 21 42 40" src="https://github.com/Harukaah/Scratch-Project/assets/141806694/33e8c821-41b9-4281-bd99-d16a842572e0">
เสียงโจมตี the mage





[[]](https://drive.google.com/file/d/1PHGbLriTPy-gDXr_vC7RP_SXM_maq5UZ/view?usp=share_link)(url)
