### ISSUE TITLE
Boss Design

### ISSUE THREAD

**Issue by archiash** [Harukaah/Scratch-Project#9]

**Comment by archiash** [comment]
1. Code name: the Mage 
Ability
- ยิง projectile โดยจะล็อกทิศทาง เป็น player current cell
- ยิง projectile ที่สามารถสะท้อนขอบจอได้ 2 ครั้ง 3 อัน โดยมีทิศทางไปทาง player แต่จะ random องศาเพิ่มเพื่อให้ projectile ทั้งสามสะท้อนขอบจอในองศาที่แตกต่างกันเพื่อเพิ่มความยากในการหลบ
- Build That Wall: สร้างกำแพงกั้นเขาวงกตให้ออกเป็น 2 ฝั่ง บังคับให้ player ใช้ ability ในการข้ามฝั่ง

**Comment by Harukaah** [comment]
mage phase 1 first design 
![mage phase 1 outlined](https://github.com/Harukaah/Scratch-Project/assets/140624361/0030f804-4ba8-42d4-8708-2c9478580281)

mage phase 2 first design
![mage phase 2](https://github.com/Harukaah/Scratch-Project/assets/140624361/907208e3-f76b-41f6-952b-4f9866818bce)

**Comment by Harukaah** [comment]
the reaper phase 1 first design
![reaper phase 1](https://github.com/Harukaah/Scratch-Project/assets/140624361/893c87de-f3fd-49c0-a711-19a3d934f370)

the reaper phase 2 first design
![the reaper phase 2](https://github.com/Harukaah/Scratch-Project/assets/140624361/5cd64e9b-a1f1-4a9e-85a8-e332ee86d621)

**Comment by Harukaah** [comment]
??? phase 1 first design
![unknown phase 3](https://github.com/Harukaah/Scratch-Project/assets/140624361/ea1c916a-71a7-4bae-ba5c-a7f324e45c8e)

??? phase 2 first design
![unknown phase 2](https://github.com/Harukaah/Scratch-Project/assets/140624361/bbc5c5e7-7187-4983-a286-64893b346577)
